Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
block_dev.c
mmcsd_core.c
sd.c
sdio.c
gpt.c
mmc.c
""")

if GetDepend('RT_USING_SDHCI'):
    src += [os.path.join('sdhci', 'sdhci.c')]
    src += [os.path.join('sdhci', 'fit-mmc.c')]
    src += [os.path.join('sdhci', 'sdhci-platform.c')]

# The set of source files associated with this SConscript file.
path = [cwd + '/../include' , cwd + '/sdhci/include']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SDIO'], CPPPATH = path)

Return('group')
